exclude_paths:
  - "tests/**"
  - "cmd/**"
  - "examples/**"
  - "internal/config/**"
  - "internal/logger/**"
  - "internal/transport/generated/**"
  - "**/mock_*"
  - "**/*_test.go"
  - "CLAUDE.md"
  - "*.md"
