FROM python:3.12-slim

WORKDIR /tests

COPY --from=ghcr.io/astral-sh/uv:latest /uv /uvx /bin/

COPY pyproject.toml .
RUN uv sync

COPY . .

ENTRYPOINT ["uv", "run", "pytest"]
CMD ["-v", "--tb=short", "--html=/reports/report.html", "--self-contained-html"]
